import type { Pool } from 'pg';

import { executeQuery, getDatabasePool } from '../../database';
import type { NaturalLanguageQueryUsageRepository } from './natural-language-query.limiter';

/**
 * The durable counters behind the natural-language query limits.
 *
 * Both statements follow `api-consumer.repository.ts`: one atomic upsert whose
 * primary key serialises concurrent admissions for the same bucket and window,
 * and whose `DO UPDATE ... WHERE request_count < limit` stops the counter at the
 * limit. An exhausted bucket therefore returns no row, which is how exhaustion is
 * reported, and further attempts cannot drive the stored count past the limit.
 */
export function createNaturalLanguageQueryUsageRepository(
  pool: Pool,
): NaturalLanguageQueryUsageRepository {
  return {
    async consume(bucket, bucketKey, windowStart, limit) {
      const result = await executeQuery<{ requestCount: number }>(
        pool,
        `INSERT INTO natural_language_query_usage
           (bucket_kind, bucket_key, window_start, request_count)
         VALUES ($1, $2, $3, 1)
         ON CONFLICT (bucket_kind, bucket_key, window_start) DO UPDATE
           SET request_count = natural_language_query_usage.request_count + 1
           WHERE natural_language_query_usage.request_count < $4
         RETURNING request_count AS "requestCount"`,
        [bucket, bucketKey, windowStart, limit],
      );

      const used = result.rows[0]?.requestCount;
      return used === undefined ? { allowed: false, used: limit } : { allowed: true, used };
    },
    async readClientSalt(usageDate) {
      // The salt is generated by the column default, so the value never exists
      // outside the database. `DO NOTHING` makes a concurrent first read of a new
      // date keep whichever row was stored, and the following select returns that
      // one row to every caller, so replicas cannot disagree about the salt.
      await executeQuery(
        pool,
        `INSERT INTO natural_language_query_client_salt (usage_date)
         VALUES ($1::date) ON CONFLICT (usage_date) DO NOTHING`,
        [usageDate],
      );

      const result = await executeQuery<{ salt: Buffer }>(
        pool,
        'SELECT salt FROM natural_language_query_client_salt WHERE usage_date = $1::date',
        [usageDate],
      );

      const salt = result.rows[0]?.salt;
      if (!salt) {
        // Nothing should remove the row between the two statements. If it
        // happens, the caller fails the request closed rather than hashing with
        // a salt of its own invention.
        throw new Error('The natural-language query client salt could not be read.');
      }

      return salt;
    },
  };
}

/** The lazily resolved repository the application uses. */
export function createDatabaseNaturalLanguageQueryUsageRepository(): NaturalLanguageQueryUsageRepository {
  let resolved: NaturalLanguageQueryUsageRepository | undefined;
  const repository = () =>
    (resolved ??= createNaturalLanguageQueryUsageRepository(getDatabasePool()));

  return {
    consume: (...args) => repository().consume(...args),
    readClientSalt: (...args) => repository().readClientSalt(...args),
  };
}
