-- Up Migration

-- The natural-language query endpoint is answered for anonymous visitors and
-- each request triggers a paid provider call, so its limits are durable rather
-- than process-local: a restart or a second replica must not hand out a fresh
-- allowance. The consumer counter tables cannot be reused for this, because both
-- key on api_consumer_id with a foreign key to api_consumer, and inventing a
-- consumer row per visitor would put fictional consumers in the administrator
-- consumer list and in the per-consumer usage reports.

-- One generic counter serves all three limits, so the three cannot drift apart
-- in implementation. The primary key serialises concurrent admissions for one
-- bucket and one window across every replica, exactly as the consumer
-- per-minute counter does.
CREATE TABLE natural_language_query_usage (
    bucket_kind   text NOT NULL CHECK (bucket_kind IN ('client_minute', 'client_day', 'global_day')),
    -- The salted client hash, or the empty string for the single global bucket.
    bucket_key    text NOT NULL,
    -- The truncated UTC minute for a minute bucket, or UTC midnight for a day bucket.
    window_start  timestamptz NOT NULL,
    request_count integer NOT NULL DEFAULT 0 CHECK (request_count >= 0),
    PRIMARY KEY (bucket_kind, bucket_key, window_start)
);

COMMENT ON TABLE natural_language_query_usage IS
    'Durable counters for the anonymous natural-language query limits; a failed read or write fails the request closed. Growth is bounded by the global daily cap, so no retention job is required.';
COMMENT ON COLUMN natural_language_query_usage.bucket_key IS
    'Salted SHA-256 of the client address, or the empty string for the global bucket. A raw IP address is never stored.';

-- A client is counted by a keyed hash of its address rather than by the address
-- itself, because an IP address is personal information and this endpoint needs
-- only to tell one client from another. The salt is generated by the database,
-- so it exists nowhere else: not in configuration, not in a deployment template
-- and not in a log. One salt per UTC date means yesterday's hashes cannot be
-- linked to today's, so the data minimises itself without a deletion job.
CREATE TABLE natural_language_query_client_salt (
    usage_date date PRIMARY KEY,
    salt       bytea NOT NULL DEFAULT gen_random_bytes(32)
);

COMMENT ON TABLE natural_language_query_client_salt IS
    'Per-UTC-date salt for hashing client addresses. Generated by pgcrypto and never leaves the database; rotating daily makes client hashes unlinkable across days.';

-- Down Migration

DROP TABLE IF EXISTS natural_language_query_client_salt;
DROP TABLE IF EXISTS natural_language_query_usage;
