// This is the authoritative Lighthouse inventory for App.tsx. A route is only
// automatically audited when it can render through the legitimate preview setup.
export const lighthouseRoutes = [
  { path: '/', access: 'public', kind: 'static', setup: 'none', baseline: true },
  {
    path: '/api',
    access: 'public',
    kind: 'static',
    setup: 'backend OpenAPI endpoint',
    baseline: true,
  },
  { path: '/competitions', access: 'public', kind: 'static', setup: 'public API', baseline: true },
  { path: '/seasons', access: 'public', kind: 'static', setup: 'public API', baseline: true },
  { path: '/fixtures', access: 'public', kind: 'static', setup: 'public API', baseline: true },
  { path: '/competitors', access: 'public', kind: 'static', setup: 'public API', baseline: true },
  { path: '/participants', access: 'public', kind: 'static', setup: 'public API', baseline: true },
  {
    path: '/dataset-releases',
    access: 'public',
    kind: 'static',
    setup: 'public API',
    baseline: true,
  },
  {
    path: '/sign-in',
    access: 'public',
    kind: 'static',
    setup: 'Supabase public configuration',
    baseline: false,
  },
  {
    path: '/competitions/:competitionId',
    access: 'public',
    kind: 'parameterised',
    setup: 'representative public competition ID',
    baseline: false,
  },
  {
    path: '/seasons/:seasonId',
    access: 'public',
    kind: 'parameterised',
    setup: 'representative public season ID',
    baseline: false,
  },
  {
    path: '/fixtures/:fixtureId',
    access: 'public',
    kind: 'parameterised',
    setup: 'representative public fixture ID',
    baseline: false,
  },
  {
    path: '/fixtures/:fixtureId/players',
    access: 'public',
    kind: 'parameterised',
    setup: 'representative public fixture ID',
    baseline: false,
  },
  {
    path: '/fixtures/:fixtureId/statistics',
    access: 'public',
    kind: 'parameterised',
    setup: 'representative public fixture ID',
    baseline: false,
  },
  {
    path: '/fixtures/:fixtureId/statistics/:statisticId',
    access: 'public',
    kind: 'parameterised',
    setup: 'representative public fixture and statistic IDs',
    baseline: false,
  },
  {
    path: '/competitors/:competitorId',
    access: 'public',
    kind: 'parameterised',
    setup: 'representative public competitor ID',
    baseline: false,
  },
  {
    path: '/participants/compare',
    access: 'public',
    kind: 'parameterised',
    setup: 'fixtureId; playerA; playerB query values',
    baseline: false,
  },
  {
    path: '/participants/:participantId',
    access: 'public',
    kind: 'parameterised',
    setup: 'representative public participant ID',
    baseline: false,
  },
  {
    path: '/dataset-releases/:version',
    access: 'public',
    kind: 'parameterised',
    setup: 'published release version',
    baseline: false,
  },
  {
    path: '/account/:section',
    access: 'authenticated',
    role: 'viewer',
    kind: 'parameterised',
    setup: 'legitimate viewer session',
    baseline: true,
  },
  {
    path: '/submissions/new',
    access: 'authenticated',
    role: 'submitter',
    kind: 'static',
    setup: 'legitimate submitter session and scope',
    baseline: true,
  },
  {
    path: '/submissions/batches',
    access: 'authenticated',
    role: 'submitter',
    kind: 'static',
    setup: 'legitimate submitter session',
    baseline: true,
  },
  {
    path: '/submissions/batches/:batchReference',
    access: 'authenticated',
    role: 'submitter',
    kind: 'parameterised',
    setup: 'legitimate submitter session and batch reference',
    baseline: false,
  },
  {
    path: '/admin',
    access: 'authenticated',
    role: 'admin',
    kind: 'static',
    setup: 'legitimate administrator session',
    baseline: true,
  },
  {
    path: '/admin/users',
    access: 'authenticated',
    role: 'admin',
    kind: 'static',
    setup: 'legitimate administrator session',
    baseline: false,
  },
  {
    path: '/admin/api-consumers',
    access: 'authenticated',
    role: 'admin',
    kind: 'static',
    setup: 'legitimate administrator session',
    baseline: true,
  },
  {
    path: '/admin/api-consumers/:consumerId',
    access: 'authenticated',
    role: 'admin',
    kind: 'parameterised',
    setup: 'legitimate administrator session and consumer ID',
    baseline: false,
  },
  {
    path: '/admin/dataset-releases/new',
    access: 'authenticated',
    role: 'admin',
    kind: 'static',
    setup: 'legitimate administrator session',
    baseline: true,
  },
  {
    path: '/reviews/batches',
    access: 'authenticated',
    role: 'admin',
    kind: 'static',
    setup: 'legitimate administrator session',
    baseline: true,
  },
  {
    path: '/reviews/batches/:batchReference',
    access: 'authenticated',
    role: 'admin',
    kind: 'parameterised',
    setup: 'legitimate administrator session and batch reference',
    baseline: false,
  },
];

export function selectableLighthouseRoutes(rawSelection) {
  const requested = rawSelection?.split(',').filter(Boolean);
  return lighthouseRoutes.filter((route) => !requested || requested.includes(route.path));
}
